/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { QueryService } from "../query.service";
import { QueryCreateInput } from "./QueryCreateInput";
import { Query } from "./Query";
import { QueryFindManyArgs } from "./QueryFindManyArgs";
import { QueryWhereUniqueInput } from "./QueryWhereUniqueInput";
import { QueryUpdateInput } from "./QueryUpdateInput";
import { ResultFindManyArgs } from "../../result/base/ResultFindManyArgs";
import { Result } from "../../result/base/Result";
import { ResultWhereUniqueInput } from "../../result/base/ResultWhereUniqueInput";

export class QueryControllerBase {
  constructor(protected readonly service: QueryService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Query })
  async createQuery(@common.Body() data: QueryCreateInput): Promise<Query> {
    return await this.service.createQuery({
      data: data,
      select: {
        createDate: true,
        createdAt: true,
        id: true,
        queryText: true,
        updatedAt: true,
        userId: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Query] })
  @ApiNestedQuery(QueryFindManyArgs)
  async queries(@common.Req() request: Request): Promise<Query[]> {
    const args = plainToClass(QueryFindManyArgs, request.query);
    return this.service.queries({
      ...args,
      select: {
        createDate: true,
        createdAt: true,
        id: true,
        queryText: true,
        updatedAt: true,
        userId: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Query })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async query(
    @common.Param() params: QueryWhereUniqueInput
  ): Promise<Query | null> {
    const result = await this.service.query({
      where: params,
      select: {
        createDate: true,
        createdAt: true,
        id: true,
        queryText: true,
        updatedAt: true,
        userId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Query })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateQuery(
    @common.Param() params: QueryWhereUniqueInput,
    @common.Body() data: QueryUpdateInput
  ): Promise<Query | null> {
    try {
      return await this.service.updateQuery({
        where: params,
        data: data,
        select: {
          createDate: true,
          createdAt: true,
          id: true,
          queryText: true,
          updatedAt: true,
          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Query })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteQuery(
    @common.Param() params: QueryWhereUniqueInput
  ): Promise<Query | null> {
    try {
      return await this.service.deleteQuery({
        where: params,
        select: {
          createDate: true,
          createdAt: true,
          id: true,
          queryText: true,
          updatedAt: true,
          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/results")
  @ApiNestedQuery(ResultFindManyArgs)
  async findResults(
    @common.Req() request: Request,
    @common.Param() params: QueryWhereUniqueInput
  ): Promise<Result[]> {
    const query = plainToClass(ResultFindManyArgs, request.query);
    const results = await this.service.findResults(params.id, {
      ...query,
      select: {
        createdAt: true,
        data: true,
        id: true,

        query: {
          select: {
            id: true,
          },
        },

        receivedDate: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/results")
  async connectResults(
    @common.Param() params: QueryWhereUniqueInput,
    @common.Body() body: ResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      results: {
        connect: body,
      },
    };
    await this.service.updateQuery({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/results")
  async updateResults(
    @common.Param() params: QueryWhereUniqueInput,
    @common.Body() body: ResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      results: {
        set: body,
      },
    };
    await this.service.updateQuery({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/results")
  async disconnectResults(
    @common.Param() params: QueryWhereUniqueInput,
    @common.Body() body: ResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      results: {
        disconnect: body,
      },
    };
    await this.service.updateQuery({
      where: params,
      data,
      select: { id: true },
    });
  }
}
